#!/bin/bash

# Copyright 2019, 2020 Johannes Marbach
#
# This file is part of AliExpress Invoice Generator, hereafter referred
# to as the program.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

npm i web-ext

if [[ ! -f pdfkit.standalone.js ]]; then
    wget https://github.com/foliojs/pdfkit/releases/download/v0.10.0/pdfkit.standalone.js
fi

command=$1

if [[ $command = run ]]; then
    flags=--verbose
elif [[ $command = build ]]; then
    flags=--overwrite-dest
fi

node_modules/web-ext/bin/web-ext $command $flags \
    --ignore-files "**/*.xcf" \
    --ignore-files "CHANGELOG.md" \
    --ignore-files "COPYING" \
    --ignore-files "README.md" \
    --ignore-files "package-lock.json" \
    --ignore-files "web-ext" \
    --ignore-files "screenshots" \
    $@
